apiVersion: v1
kind: Service
metadata:
  name: {{ .AlertManagerServiceName }}
  namespace: {{ .Namespace }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: alertmanager-k8s-tls
  labels:
    application-monitoring: "true"
spec:
  ports:
    - name: web
      port: 9091
      protocol: TCP
      targetPort: oproxy
  selector:
    alertmanager: {{ .ApplicationMonitoringName }}
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP