apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .GrafanaOperatorName }}"
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "{{ .GrafanaOperatorName }}"
  template:
    metadata:
      labels:
        name: "{{ .GrafanaOperatorName }}"
    spec:
      serviceAccountName: grafana-operator
      containers:
        - name: "{{ .GrafanaOperatorName }}"
          image: "{{ .ImageGrafanaOperator }}:{{ .ImageTagGrafanaOperator }}"
          args:
            - '--grafana-image={{ .ImageGrafana }}'
            - '--grafana-image-tag={{ .ImageTagGrafana }}'
            - '--scan-all'
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - "{{ .GrafanaOperatorName }}"
          imagePullPolicy: Always
          env:
            - name: TEMPLATE_PATH
              value: /usr/local/bin/templates
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "{{ .GrafanaOperatorName }}"
